### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Why are you requiring all of larvel?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Also, the latest laravel version is 5.2.

**Comment by reinink** [comment]
Well, I want this adapter to work with 4.x as well. This adapter basically just uses HttpFoundation, but I wanted to include Laravel just incase my tests use Laravel specific stuff.

**Comment by reinink** [comment]
However, I should probably just include that in require-dev then.

**Comment by GrahamCampbell** [comment]
Yeh, though, atm, you're preventing the use outside of laravel, like, in lumen, for example, and also preventing the usage in any actual laravel 5 apps.

**Comment by GrahamCampbell** [comment]
Why require-dev? There are no tests, and no code from laravel is actually used? This requirement is unneeded.

**Comment by GrahamCampbell** [comment]
Maybe, you should add it to "suggest" though, rather than "require"?

**Comment by reinink** [comment]
Fair enough, I need to add some tests here yet. Very good point on not working with L5. I'll fix this up. Thanks for catching me when I fall Graham! :+1:

**Comment by GrahamCampbell** [comment]
No worries. I keep an eye out for laravel stuff happening in the php league. ;)

**Comment by reinink** [comment]
I'm glad you do!

**Comment by reinink** [comment]
LOL, I didn't even notice this was a PR, and I just fixed it here: b525e33e32940f3b047d6ca357131aba0e973e72

Should be good now.

**Comment by GrahamCampbell** [comment]
Great. :)

**Pull request closed without merging**
